# Generated by Django 3.2.25 on 2025-02-24 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('param_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('param_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('param_4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('param_5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.machine')),
            ],
        ),
    ]
