# Generated by Django 3.2.25 on 2025-02-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_machine_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='note',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
