# Generated by Django 3.2.25 on 2025-02-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='task',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
