# Generated by Django 3.2.25 on 2025-02-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_machine_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='param_0',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='param_6',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='param_7',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='param_8',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='param_9',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
    ]
