# Generated by Django 3.2.25 on 2025-03-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_machine_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='param_0',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='param_1',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='param_2',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='param_3',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='param_4',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='param_5',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='param_6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='param_7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='param_8',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='param_9',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
