# Generated by Django 3.2.25 on 2025-03-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_alter_report_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixvar',
            old_name='param_1',
            new_name='rate_threading',
        ),
        migrations.RenameField(
            model_name='fixvar',
            old_name='param_2',
            new_name='rate_welding',
        ),
    ]
